/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 car.gltf --transform
Author: Renafox (https://sketchfab.com/kryik1023)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/old-rusty-car-95baa20ebc5d4d2e869f0b549be838fe
Title: Old Rusty Car
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Car(props) {
  const { nodes, materials } = useGLTF("/car-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Object006_Material_#294_0"].geometry}
        material={materials.Material_294}
        position={[0, -4.76, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["Object007_Material_#295_0"].geometry}
        material={materials.Material_295}
        position={[0, -4.76, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["Plane001_Material_#316_0"].geometry}
        material={materials.Material_316}
        position={[2.13, 0, -46.35]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/car-transformed.glb");
